# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Throughline < Formula
  desc "Local, headless coordination state layer for human/agent workflows."
  homepage "https://github.com/dennisschroeder/throughline"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dennisschroeder/throughline/releases/download/v0.5.0/throughline_0.5.0_darwin_amd64.tar.gz"
      sha256 "d9f464046480221cba0da5532952f3fa0b2e7215f5beca3482ca028e6b9eed16"

      define_method(:install) do
        bin.install "throughline"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dennisschroeder/throughline/releases/download/v0.5.0/throughline_0.5.0_darwin_arm64.tar.gz"
      sha256 "3653f53b7407f1ce4324c7eecfc5ba87e58788aca7a13abb5fb671a0d9d60071"

      define_method(:install) do
        bin.install "throughline"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dennisschroeder/throughline/releases/download/v0.5.0/throughline_0.5.0_linux_amd64.tar.gz"
      sha256 "f5063efca9c3098e36bd784ea6cca8ed434dd8187aea65a82e55153c7253493a"
      define_method(:install) do
        bin.install "throughline"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dennisschroeder/throughline/releases/download/v0.5.0/throughline_0.5.0_linux_arm64.tar.gz"
      sha256 "4d116c1ae01fa5f82583252443a22d04e4c052ccf17c6ba5b2e2a1c168d1bdf7"
      define_method(:install) do
        bin.install "throughline"
      end
    end
  end

  test do
    system "#{bin}/throughline", "version"
  end
end
