# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Throughline < Formula
  desc "Local, headless coordination state layer for human/agent workflows."
  homepage "https://github.com/dennisschroeder/throughline"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dennisschroeder/throughline/releases/download/v0.4.0/throughline_0.4.0_darwin_amd64.tar.gz"
      sha256 "961e78d70e2af2b5283f9a34a9b6ba4de6b0e1e2c763cd3f51ca8f19f5e6a47e"

      define_method(:install) do
        bin.install "throughline"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dennisschroeder/throughline/releases/download/v0.4.0/throughline_0.4.0_darwin_arm64.tar.gz"
      sha256 "db5c52591f537204c9de887b308cc492dccccaf22c0e938fb57275d567e1819c"

      define_method(:install) do
        bin.install "throughline"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dennisschroeder/throughline/releases/download/v0.4.0/throughline_0.4.0_linux_amd64.tar.gz"
      sha256 "f4105cf2358e6e7e8fdd485c6200d0d0acb14e9e77c6216ac572ccf006abb2df"
      define_method(:install) do
        bin.install "throughline"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dennisschroeder/throughline/releases/download/v0.4.0/throughline_0.4.0_linux_arm64.tar.gz"
      sha256 "1962bae3810a48e60a570be105c66beba4e4a91faa5a71a3824c6ac08137b8ff"
      define_method(:install) do
        bin.install "throughline"
      end
    end
  end

  test do
    system "#{bin}/throughline", "version"
  end
end
