# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Throughline < Formula
  desc "Local, headless coordination state layer for human/agent workflows."
  homepage "https://github.com/dennisschroeder/throughline"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dennisschroeder/throughline/releases/download/v0.6.0/throughline_0.6.0_darwin_amd64.tar.gz"
      sha256 "51f63e6e47d0323152150dcc1590366b52913c0db7db0acc2bbd9e7b6c30c649"

      define_method(:install) do
        bin.install "throughline"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dennisschroeder/throughline/releases/download/v0.6.0/throughline_0.6.0_darwin_arm64.tar.gz"
      sha256 "4c96aa7cee28b48e229c1888bf230ed1b0f0de85f3db60bd4f2d0b78c22fa1d6"

      define_method(:install) do
        bin.install "throughline"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dennisschroeder/throughline/releases/download/v0.6.0/throughline_0.6.0_linux_amd64.tar.gz"
      sha256 "59496710125b0a2894c5568d9eab0a8813aa0b488e7daa174dcdfbe6f316d15d"
      define_method(:install) do
        bin.install "throughline"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dennisschroeder/throughline/releases/download/v0.6.0/throughline_0.6.0_linux_arm64.tar.gz"
      sha256 "5bddf83f77814ddae09a224e39907c6e07f1b40a2faf514f8455efad7b3be0b1"
      define_method(:install) do
        bin.install "throughline"
      end
    end
  end

  test do
    system "#{bin}/throughline", "version"
  end
end
